# SQL RPGLE Source build rules

SECTION.PGM: SECTION.SQLRPGLE
NEWMBR1.PGM: NEWMBR1.RPGLE

# Add dependencies if SECTION uses database files, e.g.:
# SECTION.MODULE: SECTION.SQLRPGLE CUSTOMERS.FILE ORDERS.FILE