# SQL RPGLE Source build rules

SECTION.PGM: SECTION.SQLRPGLE
TEST1MOD1.MODULE: test1mod1.rpgle
TEST1BND1.BNDDIR: TEST1BND1.BNDDIR TEST1MOD1.MODULE 
TEST1PGM1.PGM: test1pgm1.rpgle


# Add dependencies if SECTION uses database files, e.g.:
# SECTION.MODULE: SECTION.SQLRPGLE CUSTOMERS.FILE ORDERS.FILE